### ISSUE TITLE
[BUG] Router crashes refine-nextjs app

### ISSUE THREAD

**Issue by khalibloo** [pankod/refine#1536]
**Describe the bug**
I created a new project using superplate with the options in the screenshot below. Upon running the app with `yarn dev`, I'm greeted with an error screen `TypeError: Cannot read properties of null (reading 'push')`. Deleting the yarn lock file and reinstalling packages does not help. The new lock file is exactly the same as the deleted one.

Using pnpm to install packages works up to a point. I'm able to see the login screen. But clicking the login button throws `TypeError: history.replace is not a function` in the console.

Issue is similar to #1233

**To Reproduce**
1. Create a new project using superplate with the options shown in the screenshot.
2. Run the app.
3. Visit the app url in your browser.
4. See first error.
5. Delete node_modules and yarn lock file.
6. Install packages with pnpm.
7. Run the app.
8. Visit the app url in your browser.
9. Attempt to login with `admin` username.
10. See second error in browser console.

**Expected behavior**
I expected to see a welcome screen or a login page.

**Screenshots**
![image](https://user-images.githubusercontent.com/6402969/153723942-c5a8b481-2767-4699-9d0c-bc061882f277.png)
![image](https://user-images.githubusercontent.com/6402969/153724031-9fbed200-99b9-41c8-8dc5-4c9025f95daf.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 96
 - Used dataProvider: simple rest

**Additional context**
Given that I'm running on windows, I removed the NODE_OPTIONS part of the dev script in the package.json.

**Comment by omeraplak** [comment]
Hey @khalibloo ,
Could you try npm instead of yarn?

**Comment by khalibloo** [comment]
@omeraplak, Woah that worked! I deleted node_modules and installed packages with npm. I suppose it means the different package managers are resolving the packages differently. Any ideas on how to fix pnpm or yarn? I find those 2 significantly better and more reliable than npm.

**Comment by omeraplak** [comment]
Hey @khalibloo ,
We've released `@pankod/refine@3.1.4` and `@pankod/refine-nextjs-router@3.1.5`. Can you approve this fix?

**Comment by khalibloo** [comment]
I created a new project with the same options as above. I can confirm it works with yarn. But when using pnpm, the error persists. `history.replace is not a function`. I can see in the pnpm lock file and in the node_modules packages that the versions are 3.1.4 for refine-core and 3.1.5 for refine-nextjs-router. No clue what's going on there.
