### ISSUE TITLE
[BUG]  Refine > 3.20  NextJs Antd  useEditableTable and useModalForm hooks do not work

### ISSUE THREAD

**Issue by clebeaupin** [pankod/refine#1944]
**Describe the bug**

On nextjs refine version greater than 3.20, some antd hooks do not work: useEditableTable and useModalForm

**To Reproduce**
1. Instantiate a nextjs refine project

```
npx superplate-cli -p refine-nextjs tutorial

✔ Cloned remote source successfully.
✔ What will be the name of your app · tutorial
✔ Do you want to use an UI Framework?: · antd
✔ Do you want to customize theme?: · css
✔ Data Provider: · custom-json-rest-data-provider
✔ Auth Provider: · custom-auth-provider
✔ Do you want to add an example page? · example-resource
✔ Do you want to customize layout? · custom-layout
✔ i18n - Internationalization: · i18n-antd
✔ Would you like to share your choices with us anonymously? · no
```

3. Edit posts list screen

Use 'useEditableTable' instead of 'useTable'i in '/src/components/posts/list.tsx'

```
const { 
    isEditing,
    saveButtonProps,
    cancelButtonProps,
    editButtonProps,
    tableProps, sorter } = useEditableTable<IPost>({});
```

```
<Table.Column<IPost>
        title="Inline Actions"
        dataIndex="inlineActions"
        key="inlineActions"
        render={(_text, record) => {
            if (isEditing(record.id!!)) {
                return (
                    <Space>
                        <SaveButton {...saveButtonProps} size="small" />
                        <Button {...cancelButtonProps} size="small">
                            Cancel
                        </Button>
                    </Space>
                );
            }
            return (
                <Space>
                    <EditButton
                        {...editButtonProps(record.id!!)}
                        size="small"
                    />
                </Space>
            );
        }}
    />
```

5. Launch server and go to posts listing page: http://localhost:3000/posts
6. You are redirected on https://api.fake-rest.refine.dev/posts/undefined 

**Expected behavior**

Inline editing must be active.
If I use the web app version of refine `npx superplate-cli -p refine-react tutorial`, it works.

**Comment by omeraplak** [comment]
Hey @clebeaupin ,
Thank you for contacting us! I've created PR #1945 . We want to release it today 🚀

**Comment by omeraplak** [comment]
Hey @clebeaupin ,
We've released [`@pankod/refine-antd@3.25.6`](https://github.com/pankod/refine/releases/tag/%40pankod%2Frefine-antd%403.25.6). Could you approve this fix?

**Comment by clebeaupin** [comment]
It does not work on my side. I still have the same behaviour

**Comment by omeraplak** [comment]
> It does not work on my side. I still have the same behaviour

Can you upgrade your Next.js dependency to the latest version? (I updated the version now on superplate)

`npm i next@latest`

**Comment by clebeaupin** [comment]
I found a fix. As you suggested, I have updated to the latest version of next.js
Then I set in next.config.js the experimental feature: `newNextLinkBehavior: true`
